import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavigationBar from "@/components/Navbar";
export default function Home() {
  return (
    <>
      <Head>
        <title>Matcha Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NavigationBar />
        <main className="bg-gray-200 w-full h-screen">
          <div className="max-w-7xl px-10 mx-auto flex items">Hello</div>
        </main>
      </div>
    </>
  );
}
